# Generated by Django 2.0.5 on 2021-01-22 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0002_registrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_description', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('Venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('Venue_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('venue_address', models.CharField(max_length=200)),
                ('venue_city', models.CharField(max_length=50)),
                ('venue_state', models.CharField(max_length=50)),
                ('venue_zipcode', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='registrant',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='events',
            name='event_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='RSVP.Venue'),
        ),
    ]
